echo -e "\033[0;36m         .                                         ."
echo -e "\033[0;36m ."
echo -e "\033[0;36m"
echo -e "\033[0;36m      dBBBBBBb  dBBBP dBBBBBBP dBBBBBb  .                       o"
echo -e "\033[0;36m       '   dB'                     BBP"
echo -e "\033[0;36m    dB'dB'dB' dBBP     dBP     dBP BB"
echo -e "\033[0;36m   dB'dB'dB' dBP      dBP     dBP  BB"
echo -e "\033[0;36m  dB'dB'dB' dBBBBP   dBP     dBBBBBBB"
echo -e "\033[0;36m"
echo -e "\033[0;36m                                   dBBBBBP  dBBBBBb  dBP    dBBBBP dBP dBBBBBBP"
echo -e "\033[0;36m          .                  .                  dB' dBP    dB'.BP"
echo -e "\033[0;36m                             |       dBP    dBBBB' dBP    dB'.BP dBP    dBP"
echo -e "\033[0;36m                           --o--    dBP    dBP    dBP    dB'.BP dBP    dBP"
echo -e "\033[0;36m                             |     dBBBBP dBP    dBBBBP dBBBBP dBP    dBP"
echo -e "\033[0;36m"
echo -e "\033[0;36m                                                                    ."
echo -e "\033[0;36m                ."
echo -e "\033[0;36m        o                  To boldly go where no"
echo -e "\033[0;36m                            shell has gone before"
